version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 585768183114.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building Docker image...
      - docker build -t wildrydes-app .
      - docker tag wildrydes-app:latest 585768183114.dkr.ecr.us-east-1.amazonaws.com/wildrydes-app:latest
  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push 585768183114.dkr.ecr.us-east-1.amazonaws.com/wildrydes-app:latest
      - printf '[{"name":"wildrydes-app","imageUri":"%s"}]' 585768183114.dkr.ecr.us-east-1.amazonaws.com/wildrydes-app:latest > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
